### PR TITLE
Add Classic300S Humidifier sensors

### PR DESCRIPTION
**Pull request by kdeyev**
Sensors were added:
Water Lack Sensor - notifies if the humidifier is out of water
Water Tank Sensor - notifies if the water tank is missing
High Humidity - notifies if the humidifier identified the high humidity 
Humidity Sensor - represents the humidity sensor

### CODE REVIEW

**Comment by formatBCE** [comment]
Hi! Thanks for your work!
Couple thoughts on it.

1. I wouldn't encourage people to use this repo for further improvements - all-in-all, there's official VeSync integration in HA, and pull-request already created for Classic300S functionality.
2. All these values are already present as attributes in humidifier entity. This will just duplicate data. For sure, someone will find sensor entities easier to use, but vast majority of users don't need separate entities - and if they do, one always can create template sensor on top of attribute.
3. Important notice: VeSync API servers become pretty laggy time to time. Lately they mostly fine, but still have issues here and there. And that fact, that each entity has to make its own requests to server, makes things a lot worse.
At the start, I even was forced to disable everything except main entity itself, because I couldn't add all three during integration setup due to lags.

**Comment by kdeyev** [comment]
Hi,
Thank you for your answer.
1. Congrats! I hope it will be merged soon.
2. To say honestly I did not know that there is an option to convert an attribute to a sensor. I personally use one of the sensors for sending notifications when the water tank is empty. 
3. I think we can solve it by Coordinator usage, let me give it a try. I'll cancel the PR for now

**Comment by formatBCE** [comment]
Yeah, I do the same notification even without template sensor - just triggering on attribute.
Coordinator would be great - we could add display and night light there as well I guess.

**Comment by kdeyev** [comment]
Ok. Please take a look at the updated PR.
I never saw VeSync API lags so I cannot test debouncing, it may require raising ```UpdateFailed``` exception.
Please let me know what you think.

**Review by formatBCE — APPROVED** [review]

**Review by formatBCE — APPROVED** [review]

**Comment by formatBCE** [comment]
Thanks for update! Will merge shortly.

**Review by formatBCE — APPROVED** [review]

**Pull request merged**
